#####
# Ambientum 1.0
# MySQl 5.6 is using the default official image, only 5.7 has differences
# on the configuration to work with Laravel/Lumen
#####
FROM mysql:5.6

# Repository/Image Maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>
