#####
# Ambientum 1.0
# vue-cli builds uses the default node image
######
FROM ambientum/node:6

# Repository/Image Maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>

# Switches back to default user
USER node-user

# Install vue-cli v2.0.x
RUN npm install -g vue-cli@2.0.0
