#####
# Ambientum 1.0
# vue-cli builds uses the default node image
######
FROM ambientum/node:6

# Repository/Image Maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>

# Switches back to default user
USER node-user

# Install vue-cli v1.3.x
RUN npm install -g vue-cli@1.3.0
