#####
# Ambientum 1.0
# MariaDB 10.2 is using the default official image.
# on the configuration to work with Laravel/Lumen
#####
FROM mariadb:10.2

# Repository/Image Maintainer
MAINTAINER Vitor Souza <vsouza@virtualsystems.com.br>