#####
# Ambientum 1.0
# vue-cli builds uses the default node image
######
FROM ambientum/node:6

# Repository/Image Maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>

# Install vue-cli v2.1.x
RUN npm install -g vue-cli@2.1.0
