#####
# Ambientum 1.0
# Redis 4.0 official image (alpine build)
#####
FROM redis:4.0-alpine

# Repository/Image Maintainer
MAINTAINER Vitor Rodrigues <vitor.rodrigues@gmail.com>

# Expose redis port
EXPOSE 6379

# Main command
CMD ["redis-server"]
