#####
# Ambientum 1.0
# MariaDB 10.0 is using the default official image.
# on the configuration to work with Laravel/Lumen
#####
FROM mariadb:10.0

# Repository/Image Maintainer
MAINTAINER Vitor Souza <vsouza@virtualsystems.com.br>