#####
# Ambientum 1.0
# Redis 3.2 official image (alpine build)
#####
FROM redis:3.2-alpine

# Repository/Image Maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>

# Expose redis port
EXPOSE 6379

# Main command
CMD ["redis-server"]
