#####
# Ambientum 1.0
# vue-cli builds uses the default node image
######
FROM ambientum/node:6

# Repository/Image Maintainer
MAINTAINER Vitor Souza <vsouza@virtualsystems.com.br>

# Install vue-cli v2.4.x
RUN npm install -g vue-cli@2.4.0
