#####
# Ambientum 1.0
# gulp-cli builds uses the default node image
######
FROM ambientum/node:6

# Repository/Image Maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>

# Install gulp 1.2.x
RUN npm install -g gulp-cli@1.2.2
