#####
# Ambientum 1.0
# MariaDB 5.5 is using the default official image.
# on the configuration to work with Laravel/Lumen
#####
FROM mariadb:5.5

# Repository/Image Maintainer
MAINTAINER Vitor Souza <vsouza@virtualsystems.com.br>
